name: 'Verify Release Tag'
description: 'Verify release tag'
inputs:
  tag:
    description: 'The release tag'
    required: true
  branch:
    description: 'The release branch to checkout'
    required: true
  githubToken:
    description: 'The token used to checkout the repo'
    required: true
outputs:
  release-version:
    description: "Release version"
    value: ${{ steps.release-version.outputs.value }}
runs:
  using: 'composite'
  steps:
    - name: Get release version
      id: release-version
      run: echo ::set-output name=value::${{ inputs.tag }}
      shell: bash

    - name: Print tag version
      run: echo ${{ steps.release-version.outputs.value }}
      shell: bash

    - uses: actions/checkout@v2
      with:
        token: ${{ inputs.githubToken }}
        ref: ${{ inputs.branch }}
        fetch-depth: 0

    - name: Get tagged branches
      id: tagged_branches
      run: echo "::set-output name=value::$(git branch --contains ${{ steps.release-version.outputs.value }} | sed 's/^[ \t\*]*//;s/[ \t]*$//' | jq -R . | jq -s .)"
      shell: bash
      
    - name: Print tagged branches
      run: echo ${{ steps.tagged_branches.outputs.value }}
      shell: bash

    - name: Fail if ${{ inputs.branch }} does not contain the tag
      run: |
        echo "Branch ${{ inputs.branch }} does not contain tag ${{ steps.release-version.outputs.value }}. Exit now!
        exit -1
      if: contains(fromJSON(steps.tagged_branches.outputs.value), inputs.branch) == false
      shell: bash
