name: 'Release server app'
description: 'Release server app'
inputs:
  addonKey:
    description: 'Addon key'
    required: true
  tag:
    description: 'The release version'
    required: true
  branch:
    description: 'The release branch to checkout'
    required: true
  githubToken:
    description: 'The token used to checkout the repo'
    required: true
  marketplaceToken:
    description: 'The marketplace token'
    required: false
runs:
  using: 'composite'
  steps:
    - name: Verify release tag
      id: verify-release-tag
      uses: ./verify-release-tag
      with:
        tag: ${{ inputs.tag }}
        branch: ${{ inputs.branch }}
        githubToken: ${{ inputs.githubToken }}

    - name: Setup node environment
      id: setup-node-env
      uses: ./setup-node

    - name: Build and upload jar files to release assets
      id: build-jars
      uses: ./build-jar
      with:
        release-version: ${{ steps.verify-release-tag.outputs.release-version }}
        branch: ${{ inputs.branch }}
        githubToken: ${{ inputs.githubToken }}

    - name: Release to marketplace
      uses: ./marketplace
      with:
        addonKey: ${{ inputs.addonKey }}
        filePath: ${{ steps.build-jar.outputs.file-path }}
        fileName: ${{ steps.build-jar.outputs.file-name }}
        version: ${{ steps.verify-release-tag.outputs.release-version }}
        marketplaceToken: ${{ inputs.marketplaceToken }}
      if: ${{ inputs.marketplaceToken }} != '' && steps.build-jar.outputs.should-bump-version == 'true'

    - name: Commit the changes to pom.xml
      run: |
        git stash apply
        git config --global user.name "DevOps"
        git config --global user.email "devops@atlasauthority.com"
        git add pom.xml
        git commit -m "Bumped version to ${{ steps.verify-release-tag.outputs.release-version }}"
        git push
      if: steps.build-jar.outputs.should-bump-version == 'true'
      shell: bash
