---
name: 'Deploy Production'
concurrency:
  group: prod
defaults:
  run:
    working-directory: connect
on:
  push:
    branches: ["main"]
jobs:
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      target: prod
    secrets: inherit
